.TH lvmdbusd 8
.SH NAME
.B lvmdbusd
.SH DESCRIPTION
.B lvmdbusd
is a service which provides a D-Bus API to the logical volume manager (lvm).

.SH USAGE
Run
.B lvmdbusd as root.

.SH OPTIONS
\fB\-\-debug\fR = Enable debug statements 
.HP
\fB\-\-udev\fR = Use udev events to trigger updates
.HP
.SH SEE ALSO
lvm(8)
